### ISSUE TITLE
Feature request: volume state/level

### ISSUE THREAD

**Issue by rogersmj** [parautenbach/hass-shairport-sync#10]
Do you think there's a way to get the volume level (and possibly set a volume level)?

Most of my other media players in Home Assistant have a volume_level attribute. I don't see that for a Shairport Sync media player:

![image](https://user-images.githubusercontent.com/20134/209863182-3775dbfd-88f2-425d-84c3-69472d4ec7ee.png)

However, when I change the volume of the Shairport Sync instance (via my iPhone, for instance), I see this on the MQTT topic:

![image](https://user-images.githubusercontent.com/20134/209863232-68e48b37-b3f8-48b7-a972-2568385e694e.png)

Pressing volume up and it looks like this:
![image](https://user-images.githubusercontent.com/20134/209864978-e68e488c-f0ae-4184-8656-98916770fc89.png)

I don't know what these numbers mean, but do you think they could be used to drive a volume_level attribute in HA?

**Comment by mill1000** [comment]
Shairport Sync does report a volume level via MQTT, but doesn't support setting an explicit volume.

From the experimentation I did, HA will only display a volume slider if the media player can set an arbitrary volume.

**Comment by parautenbach** [comment]
Yeah, when I built this I looked into this, but it didn't seem feasible. There are various volume controls involved. I couldn't think of a decent workaround, so stuck with relative volume setting. If someone has a solid implementation and wants to provide it as a PR, I'm obviously open to that. For now, I'll close it.
