### ISSUE TITLE
Recommendation for a docker-compose.yaml

### ISSUE THREAD

**Issue by jperquin** [parautenbach/hass-shairport-sync#20]
Hi there,

Kudo's for this development.

Any chance you can recommend a docker-compose config that works right out of the box with mqtt so that it reflects the compile options you suggested ( ./configure --with-mqtt-client --with-metadata)?

Thanks in advance, Joost

**Comment by parautenbach** [comment]
Thank you. 

Unfortunately, I don't have a recommendation for you.

**Comment by mill1000** [comment]
Here's the MQTT config I use if that helps.
```
mqtt =
{
    enabled = "yes";
    hostname = "<redacted>";
    port = 1883;
    username = "<redacted>";
    password = "<redacted>";
    topic = "stereoberry/shairport";
    publish_parsed = "yes";
    publish_cover = "yes";
    enable_remote = "yes";
};
```

**Comment by jperquin** [comment]
> Here's the MQTT config I use if that helps.
> 
> ```
> mqtt =
> {
>     enabled = "yes";
>     hostname = "<redacted>";
>     port = 1883;
>     username = "<redacted>";
>     password = "<redacted>";
>     topic = "stereoberry/shairport";
>     publish_parsed = "yes";
>     publish_cover = "yes";
>     enable_remote = "yes";
> };
> ```

Thanks, mine looks the same.

Not sure if the standard docker image I pulled was compiled with MQTT enabled..

JP

**Comment by mill1000** [comment]
I haven't tried the docker image, but if you exec a shell in the container you should be able to check.
e.g. 
```shell
pi@StereoBerry:~ $ shairport-sync --version
4.2-alac-OpenSSL-Avahi-ALSA-soxr-metadata-mqtt-mpris-sysconfdir:/etc
```

**Comment by jperquin** [comment]
That's a step in the right direction! :-)

This is what I am getting:

/ # shairport-sync --version
4.3.1-dirty-AirPlay2-smi10-alac-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

Still no chatter on my MQTT broker though..

**Comment by mill1000** [comment]
Ok, try running with `-vv` and look in the output for MQTT messages. It should let you know if it connected ok

**Comment by jperquin** [comment]
> Ok, try running with `-vv` and look in the output for MQTT messages. It should let you know if it connected ok

I am running shairport in docker. Where do I find the output?

**Comment by mill1000** [comment]
There's a `docker logs` command, or you could exec into the container and run shairport directly.
