### ISSUE TITLE
Information: remote control stopped working

### ISSUE THREAD

**Issue by hanneshier** [parautenbach/hass-shairport-sync#22]
Just as a reference for people having the same problem: the remote control feature seems to have stopped working on the iOS/tvOS side. See this [issue on shairport-sync](https://github.com/mikebrady/shairport-sync/issues/1858) for a discussion on the topic. Cover and metadata remains working fine.

**Comment by parautenbach** [comment]
Thanks for reporting this. 

Fore reference, from Mike Brady on the linked issue:

> Thanks for the post. Unfortunately, this seems to be due to a change at the player (e.g. the Music app). The issue is that some changes have occurred in recent versions of iOS and Mac such that the players don't respond to the remote control commands being sent by Shairport Sync. It's not just confined to Shairport Sync either -- it [seems](https://appleinsider.com/articles/24/03/25/third-party-apple-tv-remotes-no-longer-working-for-some-after-tvos-174-update) to be a general problem.

**Comment by MSL-DA** [comment]
Does anyone know if this has been fixed with iOS18?

**Comment by janstadt** [comment]
Any updates on this?

**Comment by iVolt1** [comment]
Since there is still no word from Apple that they will fix the non-Apple remotes not working problem, can something prominent go up on the readme.md so people don't start going down that path only to find out later it won't work?

Thanks for the great integration.
