### ISSUE TITLE
Use enum.StrEnum instead of StrEnum

### ISSUE THREAD

**Issue by guix77** [parautenbach/hass-shairport-sync#23]
`StrEnum was used from shairport_sync, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'shairport_sync' custom integration`

**Comment by parautenbach** [comment]
Fixed in the upcomgin 1.4.0 release.

**Comment by parautenbach** [comment]
Released
