### ISSUE TITLE
Deprecated async_forward_entry_setup

### ISSUE THREAD

**Issue by guix77** [parautenbach/hass-shairport-sync#24]
`Detected that custom integration 'shairport_sync' calls async_forward_entry_setup for integration, shairport_sync with title: shairport_sync shairport and entry_id: 093eb43610c956d99145527a01b9699a, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/shairport_sync/__init__.py, line 12: hass.async_create_task(, please create a bug report at https://github.com/parautenbach/hass-shairport-sync/issues`

**Comment by parautenbach** [comment]
Fixed in the upcomgin 1.4.0 release.

**Comment by parautenbach** [comment]
Released
