### ISSUE TITLE
Metadata not showing on play after inactivity

### ISSUE THREAD

**Issue by dfanica** [parautenbach/hass-shairport-sync#25]
If the player is in an inactive state (not playing or paused for a few minutes) it goes into a state where no metadata is showing.
If the playback is resumed, or the initial play request happens, the cover is being set but not the rest of the metadata. It gets updated with any other action after this.

E.g. 
![Screenshot 2024-08-05 at 10 15 38](https://github.com/user-attachments/assets/11c7f59c-5971-47c2-acda-361389a2aa2f)
This is after the first playback. Cover is showing but no metadata information.

![Screenshot 2024-08-05 at 10 16 57](https://github.com/user-attachments/assets/a52c8fcc-6d1a-463a-8681-28e4dea491fa)
If I pause the metadata updates. Any other action here would update the metadata so next or previous song would work too.

**Comment by parautenbach** [comment]
This is likely due to Sharport Sync itself: It sends a stream end after some inactivity.

**Comment by parautenbach** [comment]
Use a tool like MQTT Explorer to inspect the topics in real-time to see if the metadata is published. If it's updated there, then it should pull through to the integration and get displayed. 

Are you using the built-in media player card in HA?

Also compare your HA, this integration and ShairportSync versions compared to what's been tested again (see the README) and report here what you have.

**Comment by parautenbach** [comment]
Closed as stale.
