### ISSUE TITLE
No file found manifest.json

### ISSUE THREAD

**Issue by dapuzz** [parautenbach/hass-shairport-sync#3]
Hi
I have installed hass-shairport-sync via HACS and after the reboot I found this row in the log:
`[custom_components.hacs] <Integration parautenbach/hass-shairport-sync> No file found 'manifest.json'`
although the manifest is there: custom_components/shairport_sync/manifest.json

Can you help me understanding this log?

Thank you

**Comment by dapuzz** [comment]
I think you should move shairport_sync in a subfolder custom_components/shairport_sync, can you double check please?

**Comment by alexisteleco** [comment]
Same here.
It's weird, as @dapuzz said, I can see the manifest in place, where it is supposed to be.

**Comment by dapuzz** [comment]
No, you are missing the custom_components subfolder in the github repository

**Comment by parautenbach** [comment]
Hi @dapuzz and @alexisteleco, would you please try now? I restructured this repo so it should work correctly with HACS now. I didn't test though but did it according to the docs.

Apologies for the delay. I've had a lot of family stuff to deal with.

**Comment by alexisteleco** [comment]
No need for apologies ;)

I reinstalled, and the error was the same, so I tried to uninstall and I was not able, then I erased the old files and installed again.

Although the files are now inside `config/custom_components/custom_components/shairport_sync`, the error is still there.
Nevertheless, it can be other type of stuff, because I am also neither able to uninstall the integration, nor able to use it.

Let me check what is happening and I will come back with more useful information.

**Comment by alexisteleco** [comment]
I erased all files related with hass-shairport-sync (now truly).
<img width="710" alt="image" src="https://user-images.githubusercontent.com/17027081/121336683-0c720b80-c91c-11eb-9dc5-8d3229dc37bb.png">

Then I erased the custom repo of hass-shairport-sync (I know that this is not necessary, but just for the sake of completeness) and restarted homeassistant.

Finally, I installed it from scratch via HACS again, but the error continues showing.
<img width="527" alt="image" src="https://user-images.githubusercontent.com/17027081/121338603-f1a09680-c91d-11eb-8cd6-e3882478c409.png">

I am not sure if the repo is located where it should be. At least it is not located at the same folder as the rest of mine:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/17027081/121338429-c9189c80-c91d-11eb-96e8-5f4030230af6.png">

By the way, in the custom_components folder shown in the screenshot, there is only a `shairport_sync` folder:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/17027081/121338926-480dd500-c91e-11eb-91c5-7e74f6e6c0f9.png">


If you need some more testing, let me know and I will try to do it.

**Comment by parautenbach** [comment]
I think it's fixed now. The `content_in_root` setting in `hacs.json` was incorrect.

**Comment by alexisteleco** [comment]
Yes! Thanks 😊
